name: Hardware Check

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
      - develop

jobs:
  kicad-check:
    name: KiCad ERC and DRC
    runs-on: self-hosted
    container:
      image: kicad/kicad:10.0
      options: --user root

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check KiCad version
        run: |
          kicad-cli --version

      - name: Run ERC on KiCad projects
        run: |
          error=0

          find . -name "*.kicad_pro" ! -path "*backup*" ! -path "*/.history/*" > projects.txt

          while read project; do
            schematic="${project%.kicad_pro}.kicad_sch"

            echo "Running ERC on $schematic"

            if ! (cd "$(dirname "$schematic")" && kicad-cli sch erc "$(basename "$schematic")" --exit-code-violations); then
              error=1
            fi

          done < projects.txt

          exit $error

      - name: Run DRC on all PCBs
        run: |
          error=0

          find . -name "*.kicad_pcb" ! -path "*backup*" ! -path "*/.history/*" > pcbs.txt

          while read file; do
            echo "Running DRC on $file"

            if ! (cd "$(dirname "$file")" && kicad-cli pcb drc "$(basename "$file")" --exit-code-violations); then
              error=1
            fi

          done < pcbs.txt

          exit $error